server:
  port: 8082
spring:
  application:
    name: BasicBack
  datasource:
    url: jdbc:mysql://localhost:3306/sticknew?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&SSL=false
    username: root
    password: zhang20061023@
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 0
  rabbitmq:
    virtual-host: /
    username: admin
    password: admin123456
    host: localhost
    port: 5672
  ai:
    openai:
      api-key:  ${OPENAI_API_KEY}
      base-url: https://api.xty.app
#      embedding:
#        options:
#          model: text-embedding-v3
#          dimensions: 1024
#jwt
Bluegod:
  security:
    jwt-key: Bluegod
    # 过期时间
    token-expired-in: 86400000
pagehelper:
  reasonable: true
  helper-dialect: mysql
mybatis:
  configuration:
    #驼峰映射开关
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mapper/*.xml
sky:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    bucket-name: zhhhandsome

l2cache:
  config:
    # 是否存储空值，默认true，防止缓存穿透
    allowNullValues: true
    # 组合缓存配置
    composite:
      # 是否全部启用一级缓存，默认false
      l1AllOpen: false
      # 是否手动启用一级缓存，默认false
      l1Manual: true
      # 手动配置走一级缓存的缓存key集合，针对单个key维度
      l1ManualKeySet:
        - userCache:user01
        - userCache:user02
        - userCache:user03
        - userCache:user04
        - "[actLimitMarkupCache:11_3]"
      # 手动配置走一级缓存的缓存名字集合，针对cacheName维度
      l1ManualCacheNameSet:
        - userCache
        - goodsCache
    # 一级缓存
    caffeine:
      # 是否自动刷新过期缓存 true 是 false 否
      autoRefreshExpireCache: false
      # 缓存刷新调度线程池的大小
      refreshPoolSize: 2
      # 缓存刷新的频率(秒)
      refreshPeriod: 10
      # 写入后过期时间(秒)
      expireAfterWrite: 180
      # 访问后过期时间(秒)
      expireAfterAccess: 180
      # 初始化大小
      initialCapacity: 1
      # 最大缓存对象个数，超过此数量时之前放入的缓存将失效
      maximumSize: 3

    # 二级缓存
    redis:
      # 全局过期时间，单位毫秒，默认不过期
      defaultExpiration: 300000
      # 每个cacheName的过期时间，单位毫秒，优先级比defaultExpiration高
      expires: {userCache: 300000,goodsCache: 50000}
      # 缓存更新时通知其他节点的topic名称 默认 cache:redis:caffeine:topic
      topic: cache:redis:caffeine:topic
logging:
  level:
    com.dlut.blockchain: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    org.springframework.web.servlet.handler: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

call:
  session:
    ttl-seconds: 180
    cleanup-interval-ms: 60000
  connection:
    cleanup-interval-ms: 30000
#配置nacos

#wechat:
#  pay:
#    enabled: true
#    mock: true # 开发联调阶段可为 true，生产置为 false
#    app-id: your-app-id
#    mch-id: your-mch-id
#    api-v3-key: your-api-v3-key
#    private-key-path: file:/path/to/your/apiclient_key.pem
#    cert-serial-no: your-cert-serial-no
#    platform-cert-path: file:/path/to/platform_cert.pem
#    notify-url: http://localhost:8080/api/pay/wechat/notify
#    refund-notify-url: http://localhost:8080/api/pay/wechat/refund/notify



